# Build the project using the Bitcraze builder docker image
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 16 * * 3'

env:
  BUILDER_IMAGE: bitcraze/builder:41

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Unit tests
      run: docker run --rm -v ${PWD}:/module ${BUILDER_IMAGE} ./tools/build/test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: docker run --rm -v ${PWD}:/module ${BUILDER_IMAGE} ./tools/build/make
    - name: Build long range
      run: |
        docker run --rm -v ${PWD}:/module ${BUILDER_IMAGE} ./tools/build/make clean
        docker run --rm -v ${PWD}:/module ${BUILDER_IMAGE} ./tools/build/make "EXTRA_CFLAGS=-DLPS_LONGER_RANGE"
